#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "Validating PHPCS:"

# Check for phpcs
which ./vendor/bin/phpcs &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PHPCS"
  exit 1
fi

RULESET=./phpcs.xml

for FILE in $STAGED_FILES
do
  ./vendor/bin/phpcs --standard="$RULESET" "$FILE"
  ./vendor/bin/phpcs --standard="$RULESET" "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "PHPCS Passed: $FILE"
  else
    echo "PHPCS Failed: $FILE"
    PASS=false
  fi
done

echo "PHPCS validation completed!"

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again."
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

exit $?
